


datasets:
	RScript processing/get_papuanlanguages.R
	
	

	
# How diverse are Papuan kinship systems relative to Global design space

# Syncretisms that are found in Papua, but not elsewhere 

# Star burst method or other way to look at 